In [1]:
# 展示结果

In [1]:
import pandas as pd
from scipy.stats import sem
disease = "EW-T2D"
path = f"/data/home/chenliang/project/XXXX-Transformer/model/MSFT-Transformer-master/results/EW-T2D/MTMFTransformer.csv"
df = pd.read_csv(path)

In [2]:
df.head()

,n_layers,num_bottleneck,lr,batch_size,use_bottleneck,btn_init,use_cross_atn,seed,mode,feature,AUC,ACC,Recall,Precision,F1
0,2,4,0.0001,16,True,embed,False,392,0,"ko,species",0.7778,0.7,0.6364,0.7778,0.7000
1,2,4,0.0001,16,True,embed,False,412,0,"ko,species",0.8889,0.8,0.9091,0.7692,0.8333
2,2,4,0.0001,16,True,embed,False,432,0,"ko,species",0.7677,0.7,0.9091,0.6667,0.7692
3,2,4,0.0001,16,True,embed,False,452,0,"ko,species",0.8485,0.8,0.8182,0.8182,0.8182
4,2,4,0.0001,16,True,embed,False,472,0,"ko,species",0.8687,0.8,0.9091,0.7692,0.8333

In [3]:
group_df = df.groupby(['n_layers', 'num_bottleneck', 'lr', 'batch_size', 'use_bottleneck', 'btn_init', 'use_cross_atn', 'mode'])

In [4]:
def get_same_paras_results(path: str, groupby_features) -> pd.DataFrame:
    df = pd.read_csv(path)
    group_df = df.groupby(groupby_features)
    avg_results = []
    for name, tmp_df in group_df:
        if tmp_df.shape[0] != 5:
            continue
        columns = list(tmp_df.columns)
        average_metrics = {k: tmp_df[k].iloc[0] for k in columns if k not in ['AUC', 'ACC', 'Recall', 'Precision', 'F1']}
        average_metrics.update({
            'Average AUC': round(tmp_df['AUC'].mean(), 4) * 100,
            'Average AUC std': round(sem(tmp_df['AUC']), 5) * 100,
            'Average ACC': round(tmp_df['ACC'].mean(), 4) * 100,
            'Average Recall': round(tmp_df['Recall'].mean(), 4) * 100,
            'Average Precision': round(tmp_df['Precision'].mean(), 4) * 100,
            'Average F1': round(tmp_df['F1'].mean(), 4) * 100,
        })
        avg_results.append(average_metrics)
    result_df = pd.DataFrame(avg_results)
    result_df =result_df.sort_values(by='Average AUC', ascending=False)
    return result_df

In [5]:
disease = "EW-T2D"
path = f"/data/home/chenliang/project/XXXX-Transformer/model/MSFT-Transformer-master/results/EW-T2D/MTMFTransformer.csv"
group_feats = ['n_layers', 'num_bottleneck', 'lr', 'batch_size', 'use_bottleneck', 'btn_init', 'use_cross_atn', 'mode']  
# group_feats = ['n_blocks', 'lr', 'batch_size', 'mode']  FT-Transformer
# group_feats = ['n_layers', 'm_layers', 'num_bottleneck', 'hidden_size', 'lr', 'batch_size', 'mode']
result_df = get_same_paras_results(path, group_feats)
result_df.head(5)

,n_layers,num_bottleneck,lr,batch_size,use_bottleneck,btn_init,use_cross_atn,seed,mode,feature,Average AUC,Average AUC std,Average ACC,Average Recall,Average Precision,Average F1
1,2,4,0.0001,16,True,embed,True,392,0,"ko,species",84.85,1.749,70.0,78.18,73.95,74.39
0,2,4,0.0001,16,True,embed,False,392,0,"ko,species",83.03,2.441,76.0,83.64,76.02,79.08

In [6]:
df = pd.read_csv(path)
df.head()

,n_layers,num_bottleneck,lr,batch_size,use_bottleneck,btn_init,use_cross_atn,seed,mode,feature,AUC,ACC,Recall,Precision,F1
0,2,4,0.0001,16,True,embed,False,392,0,"ko,species",0.7778,0.7,0.6364,0.7778,0.7000
1,2,4,0.0001,16,True,embed,False,412,0,"ko,species",0.8889,0.8,0.9091,0.7692,0.8333
2,2,4,0.0001,16,True,embed,False,432,0,"ko,species",0.7677,0.7,0.9091,0.6667,0.7692
3,2,4,0.0001,16,True,embed,False,452,0,"ko,species",0.8485,0.8,0.8182,0.8182,0.8182
4,2,4,0.0001,16,True,embed,False,472,0,"ko,species",0.8687,0.8,0.9091,0.7692,0.8333

In [7]:
s = """
0.3	60.0±3.5	60.8±2.9	58.7±1.4	64.7±2.9
0.1	59.1±4.6	59.7±3.1	61.7±2.6	64.7±4.0
0.05	60.2±2.7	59.2±3.2	60.9±4.1	64.6±4.3
0.0	61.5±4.2	61.0±3.3	62.2±3.3	67.7±2.9
""".replace("±", '\t').strip().split("\n")

In [8]:
for row in s:
    row = row.split("\t")
    level = row[0]
    res = f"& {level} & "
    row = row[1:]
    for i in range(int(len(row)/2)):
        res += f"{row[2 * i]}\%({row[2 * i + 1]}\%) & "
    print(res[:-2] + "\\\\")

& 0.3 & 60.0\%(3.5\%) & 60.8\%(2.9\%) & 58.7\%(1.4\%) & 64.7\%(2.9\%) \\
& 0.1 & 59.1\%(4.6\%) & 59.7\%(3.1\%) & 61.7\%(2.6\%) & 64.7\%(4.0\%) \\
& 0.05 & 60.2\%(2.7\%) & 59.2\%(3.2\%) & 60.9\%(4.1\%) & 64.6\%(4.3\%) \\
& 0.0 & 61.5\%(4.2\%) & 61.0\%(3.3\%) & 62.2\%(3.3\%) & 67.7\%(2.9\%) \\

In [18]:
res

'& 0.0 & 82.6\\%(3.1\\%) & 82.2\\%(2.1\\%) & 83.2\\%(4.2\\%) & 87.5\\%(4.1\\%) & '